### ISSUE TITLE
NeP.Interface:Fetch('NeP_CombatHelper', 'Targets', true) always returns true?

### ISSUE THREAD

**Issue by heistcode** [MrTheSoulz/NerdPack-CombatHelper#6]
[NeP.Interface:Fetch('NeP_CombatHelper', 'Targets', true)](https://github.com/MrTheSoulz/NerdPack-CombatHelper/blob/master/core.lua#L40) in combat helper seems to always return true even when unset
/dump NeP.Interface:Fetch('NeP_CombatHelper', 'Targets', true)
might want to change to NeP.Interface:Fetch('NeP_CombatHelper', 'Targets')? or Fix Fetch

**Comment by MrTheSoulz** [comment]
There erros comes from here, default should only return when `Data[key1][key2]` is nil, im gonna have to add some if's...
```lua
function NeP.Config:Read(key1, key2, default)
	return Data[key1] and Data[key1][key2] or default
end
```

**Comment by MrTheSoulz** [comment]
fixed in: https://github.com/MrTheSoulz/NerdPack/commit/132d5d646537c2b4932894ce7f66abbe184731e5
